### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by net-tech** [School-Simplified-HR-Automations/HR-Automation#24]
_1. This message can be edited by anyone. Click the 3 dots . . . and then select edit to mark something off the to-do list._
_2. Preferably link an issue and assignee for each task that needs to be done.__

- [ ] HRIS Ticket System
- [ ] HRIS Onboarding
- [ ] HRIS Application Review
- [ ] HRIS Job Postings
- [ ] Strike and censure removal tools
- [ ] Staff Count
- [x] #25 - Staff List
- [x] #23
- [x] #27
